import { IsMongoId, IsNotEmpty, IsOptional, IsString } from 'class-validator';
import { Schema as MongooseSchema } from 'mongoose';

export class CreateSessionDto {
  @IsNotEmpty({ message: 'กรุณาระบุรหัสสาขา' })
  @IsMongoId({ message: 'รหัสสาขาไม่ถูกต้อง' })
  readonly branchId: MongooseSchema.Types.ObjectId;

  @IsNotEmpty({ message: 'กรุณาระบุรหัสโต๊ะ' })
  @IsMongoId({ message: 'รหัสโต๊ะไม่ถูกต้อง' })
  readonly tableId: MongooseSchema.Types.ObjectId;

  @IsOptional()
  @IsString()
  readonly qrCode?: string; // Usually generated by service

  @IsNotEmpty({ message: 'กรุณาระบุชื่อลูกค้า' })
  @IsString()
  readonly userLabel: string;
}
